esphome:
  name: esp32-mi-flora

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

wifi:
  ssid: "HuggingFace Guests"
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (in case of connection issues)
  ap:
    ssid: "ESP32_Fallback"

# Example configuration entry
http_request:
  useragent: esphome/device
  verify_ssl: false
  timeout: 10s

logger:
  level: DEBUG

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          ESP_LOGD("ble_adv", "Detected BLE device:");
          ESP_LOGD("ble_adv", "  Address: %s", x.address_str().c_str());
          ESP_LOGD("ble_adv", "  RSSI: %d", x.get_rssi());
          std::string device_name = x.get_name();
          if (!device_name.empty()) {
            ESP_LOGD("ble_adv", "  Name: %s", device_name.c_str());
          }